// <auto-generated />
namespace SGOALB_BACK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cotizaciondetalle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cotizaciondetalle));
        
        string IMigrationMetadata.Id
        {
            get { return "202107150244583_Cotizacion-detalle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
